### ISSUE TITLE
In setup, check for the existance of the media directory and attempt creation if it doesn't exist.

### ISSUE THREAD

**Issue by tech10** [albertobeta/PodcastGenerator#10]
The easy fix is to manually create the media directory or include it in the git repo, but to make things easier for the end user, the setup script should probably create it if it doesn't exist. I received some warnings.

    Warning: fopen(../media/test.txt): failed to open stream: No such file or directory in /srv/www/public_html/podcastgen/setup/set_permissions.php on line 42

    Warning: fwrite() expects parameter 1 to be resource, boolean given in /srv/www/public_html/podcastgen/setup/set_permissions.php on line 44

    Warning: fclose() expects parameter 1 to be resource, boolean given in /srv/www/public_html/podcastgen/setup/set_permissions.php on line 45

    Warning: chmod(): No such file or directory in /srv/www/public_html/podcastgen/setup/set_permissions.php on line 114

This could apply to the images directory as well.

**Comment by albertobeta** [comment]
Thanks for the comment. Most of the users download PG stable (which includes these directories) from the official website on SourceForge: 
http://podcastgen.sourceforge.net/download
So I never noticed. An option would be including two simple files (e.g. txt) in the aforementioned folders so that they are actually pushed to github (empty folders are not pushed to the repo). Anyway, I'll definitely fix this issue for the next version of PG so that people downloading it directly from github won't have issues with the setup. Thanks again for pointing that out.

**Comment by albertobeta** [comment]
Done.
