### ISSUE TITLE
adding podtrac to podcastgenerator

### ISSUE THREAD

**Issue by Disciplemattias** [albertobeta/PodcastGenerator#145]
I have been trying to ad podtrac to my podcastgenerator podcast using this link

blue box in link below:

http://www.podcastgenerator.net/documentation/FAQ-change-RSS-URL

But in my podtrac account there is no account number. So it doesnt work.

Any idea how to add podtrack to podcast generator?

If using feedburner then exactly how to add podtrac using feedburner?

**Comment by madsha** [comment]
Hi Mattias,

I had the same problem, also confused about not having an account number...
Alberto guided me in doing a small hack, changing one line in the file 'functions.php' located in the 'core' folder.

Change line 1387 from:
<enclosure url="'.$url.$upload_dir.$singleFileName.'" length="'.$file_size.'" type="'.$filemimetype.'"/>

to:
<enclosure url="'."http://dts.podtrac.com/redirect.mp3/kkb-lyd.dk/maanedens/".$upload_dir.$singleFileName.'" length="'.$file_size.'" type="'.$filemimetype.'"/>

Use your own URL instead of 'kkb-lyd.dk/maanedens' :-)

Hope this works for you!

/Mads Hansen

**Comment by madsha** [comment]
Huh - it ate a line of my reply, anyway, I think you get the idea :-)
