### ISSUE TITLE
Is this project alive anymore?

### ISSUE THREAD

**Issue by vrdriver** [albertobeta/PodcastGenerator#36]
Hi, 
The last real update I've seen is from 2 years ago, and a bunch of forks. 
I also saw that it's still using md5 hashes for password encryption.
Regardless of keeping the requirements low, can we modernise this and bring it up to the latest best practice and merge the latest bug fixes in to the main branch?
I'm purely making suggestions and asking questions. 
But in reality, Is this project still alive my the original maintainer?
Ta.

**Comment by albertobeta** [comment]
Hi @Steve, 
thanks for your comment, it's very relevant. 
**Yes the project is still alive**, and I'm officially maintaining it since 2006. I put a lot of effort in the past 11 years to keep it up and running.

It is true that, due to the lack of time, I haven't released a major update for a (long) while. However, the current version of PG is still stable and doesn't present any known security issue: I have always committed to not compromise with security and I will release an official version with a fix in less than 48 hours if a serious security issue (e.g. cross site scripting etc.) is discovered.

This said, as you correctly point out, the project needs a nice face lifting (it's about time!), not only in regards to details such as switching from md5 to bcrypt or similar, but also in terms of architecture! So many functions and old-fashioned legacy code... 😱 but you know what? I'm keeping PG alive (and as "healthy" as possible) since it's is still working and currently powering [tens of thousands of podcasts](https://www.google.com/search?q=%22powered+by+podcast+generator%22&oq=%22powered+by+podcast+generator%22&aqs=chrome..69i57.147j0j7&sourceid=chrome&ie=UTF-8) 💪

Rather than refactoring the existing code I think it makes more sense to **rewrite PG from scratch**, using more modern OOP paradigms and good practices (e.g. SOLID). And besides that... It's time to use a MySQL DB (enough with text-based files!) since most of the hosting services today, even the cheapest ones, offer a LAMP setup out of the box. This is in line with my vision of _keeping the requirements as low as possible_.

I was planning to start to rewrite PG last summer, yet I had to postpone due to lack of time. What I did as a start was moving the support requests from the old Sourceforge to Github, so we can collect issues, pull requests, feature requests etc. in a single place.
The plan is collecting the requirements here until the end of this year, convert them into user stories and tasks and... rewrite Podcast Generator from scratch to release the new branch 3 early next year 🚀 
This won't be easy if I'm alone. **I could use some help**. Anyone volunteering? 👆

Please feel free to share this message with anyone that could be interested and spread the voice 📢
Cheers
Alberto

**Comment by vrdriver** [comment]
Hi Alberto,

Thanks for the prompt reply. It was great to wake up this morning and see your message and learn that it's still on-going and that you have plans to keep it going and revive it. It was hard to tell from the home page that there was a github account for it.
It's a great effort to keep it going for that long, so well done.
I had a quick look at your Linked-In profile, and I can see why you are so busy.
I agree with all those suggestions you made, especially with the MySQL statements.  At the moment the code looks fairly simple to follow (which is good), and I'm glad it is secure. I even looked to see if there where any [CVEs on it.](https://www.cvedetails.com/vulnerability-list/vendor_id-7843/Podcast-Generator.html)  :) 
I think I'll use it and just modify the front end template a little. If I find/create anything of significance I'm happy to submit pull requests for you, but at this stage I don't think I'm up to the task of helping rewrite it, as my knowledge/use of OOP isn't A grade at this stage.
As I said though, super stoked it's still active. Great job on it so far though.
Cheers,
Steve

**Comment by alwa** [comment]
>  I could use some help. Anyone volunteering? 👆

I think that it might help (to find people with the right skill set) if you started to describe your thoughts on the technical solution for the new version. For example: Will it be based on PHP?

**Comment by albertobeta** [comment]
The context: PG was [originally created for teachers and educators](http://www.podcastgenerator.net/credits#story) who often have a very low (or no) budget and sometimes limited technical skills. 
The idea with the new version is following the same philosophy as the previous releases which made PG so popular as podcast publishing web app: **avoid complexity**. We do not want to ask users to "deploy on Heroku": anyone should be able to install PG via a simple web-based setup wizard. 

We will use PHP as main language and intentionally **keep requirements as low as possible** so PG can run on most hosting spaces, including the cheap ones: no extra PHP modules to install via composer etc... just a very standard and basic LAMP configuration.  

In this new version I would (finally!) add a MySQL DB, as opposed to the current release that relies on xml files (this was due to "historical reasons" and has not so much sense today). 

The idea is that the core of PG will be a RESTful API written in PHP with authentication and a number of endpoints to CRUD objects (e.g. episodes).

On top of the API, we'll have the front-end side written HTML5/CSS3/JS (no frameworks such as Angular or React that require installation in the server, let's keep it accessible to everyone). The front-end will act as a simple client for the API and it will be fully rendered in the browser. 
The UI will be simple and responsive (bootstrap, bootstrap, bootstrap) for both the public and the admin areas. 
The challenges in the front-end side will be the localization in different languages (probably we'll have to use some out-of-the-box solution that comes with PHP, such as gettext) and a "theme engine" so that users can easily create their own theme and customize colors, add their logo etc...

I'll need more help with the front-end part. It would be great if I could take care of the API and someone helped with the UI.

As an future extra, once the API will be ready, we could also design & code native (or "react-native" ;) mobile apps for iOS and Android that simply connect to the API and allow users to manage their episodes on the go.

**Comment by RobertBozic** [comment]
Hi Alberto,
Thanks for all your work.
When you collect ideas for version 3, some my thoughts:
- Would it be possible for PGv3 to take care of more podcast with one single installation?
- media files would be separated by directories
/media/podcast1
          /podcast2
          /podcast3...
It will be nice for radio stations use (useful for a multi-podcast radio)
All good in 2018!

**Comment by sleepysunday1979** [comment]
apologies for adding to this, but i was unsure of where else i could put it (i had sent alberto an email about helping out with v3, but understand that he's an extremely busy man!).  i thought a few users out there may find this helpful...

i started using PGv2.7 about a week ago, but wasn't happy with the themes.  so i created a bit of an adaptable theme which can be configured a little bit (or actually a lot) more than the current set.  have a look at the project below if you wish to use it, and i'm happy to take on any feature requests or comments.  (bear in mind, i'm not really a coder, i generally only code for small audiences, and more than likely have a lot of bad habits which come from being self-taught!).  i've had to put in a few hacks between js+php in order to get the customisation of theme working, but it seems to be working as intended so far.

https://github.com/sleepysunday1979/pg-studiotheme/

**Comment by matterik** [comment]
I have used podcast generator now for over a year to power a podast using a network access storage. 

My experience is that when something goes wrong applications that uses a mysql database are much harder to recover. 

I have had problem recovering my wordpress blogs after crashes.

but the podcast generator that doesnt use mysql but only uses php has always worked without fault after crashes and after reinstalling of operating system. 

So I have been happy that podcast generator does not use a mysql databse.

**Comment by alwa** [comment]
@sleepysunday1979 Maybe you can send a pull request to @albertobeta with your fix? Would be sad if a fork is needed for this project.

One feature that I think would be beneficial to many is this: https://github.com/albertobeta/PodcastGenerator/issues/31

I think that many podcasts have these different categories and that it would give all listeners a better experience if this could be marked up properly

**Comment by 5thtradition** [comment]
I am currently using the last version of Podhawk to host my podcast site. Is there any experience with converting a podhawk database podcast site and all the tagging over to podcast generator. I am looking for a more current podcast engine to use and am not sure if I am locked in to Podhawk or is there a conversation method possible.

**Comment by dougdalton** [comment]
What is the target for 3.0? is there a release or email list for updates?

**Comment by iMorpheus** [comment]
Please, no MySQL! Flat-files are easy to maintain and transfer from server to server. XML, RSS and JSON feeds stored in flat-files requires only PHP.

MySQL will force me to remain on 2.7 OR to find another solution. @albertobeta

**Comment by Go-rom** [comment]
Hello Alberto

I'm not a developer but i can help for the french translation.
Feel free to tell us when it will be ready for translation.

Anyway, thank you for this great open source podcast tool.

Regards

**Comment by DRPalla** [comment]
I would love to see this on a local MySQL db. Then a nice search engine can be added to PG. It would be cool to search on part of an episode 'Name' or 'Description.' Having a search list display inside PG just like a 'Category' list would be sweet.
r

**Comment by dpDesignz** [comment]
I'm a full stack developer in New  Zealand who has been using your product for years and would love to help in whatever way I can.

**Comment by albertobeta** [comment]
@dpDesignz glad to hear that, could you pls reach out via email and we'll take it from there
support@podcastgenerator.net
thanks

**Comment by mcrump001** [comment]
If there is a concern around mysql would sqlite be an acceptable alternative?  I'm not sure how prevalent it is on hosting sites though.

**Comment by gerega** [comment]
This project is dead. Move on...

**Comment by Go-rom** [comment]
Project might dead but PG2 is still usable. Hope that a fork will start because it's a very good tool.

**Comment by gerega** [comment]
Yup, it depends how you define "usable".

**Comment by albertobeta** [comment]
Dear all, quick update: https://twitter.com/albertobeta/status/1160141717531713536
I spent over a decade on Podcast Generator. Due to lack of time, I'm now **looking for someone to take over the project**. Feel free to reach out here or via email: alberto@betella.net

**Comment by emilengler** [comment]
I am working on a rewrite now.
Progress here #147

**Comment by vrdriver** [comment]
These new developments are great, and I am happy to close this ticket. Would it be worth making a link to the new project/version in the readme of the front page of this initial project?

**Comment by Go-rom** [comment]
Yes, great news ! Thank you @emilengler

**Comment by emilengler** [comment]
> Would it be worth making a link to the new project/version in the readme of the front page of this initial project?
No, I will open a PR once my fork is stable

**Comment by emilengler** [comment]
3.0 will be released tomorrow (31th of December).
I think this issue can be closed now :-)

**Comment by emilengler** [comment]
PG 3.0 is out now!
https://github.com/albertobeta/PodcastGenerator/releases/tag/v3.0
