### ISSUE TITLE
FTP Feature

### ISSUE THREAD

**Issue by ElGatoSaez** [albertobeta/PodcastGenerator#4]
Hello, I'm ElGatoSaez.
I wanted to say that this is great. One of the best projects i've ever seen.
I'm having some problems with FTP Feature. ¿In which format should i upload them?
I press the continue button and nothing happens. I uploaded the file on the media folder.

Please, help.
Again, this is a great project.
Sebastián.

**Comment by albertobeta** [comment]
Hola Sebastián,
thank you. The FTP feature should work out of the box, in principle it will index any file extension that is [specified here](https://github.com/albertobeta/PodcastGenerator/blob/master/components/supported_media/supported_media.xml). If nothing happens, check the server logs or enable PHP display of warnings and error to see if you have any particular issue. Also to test it, try to upload into the media folder just 1 very small mp3 file called abc.mp3 (with no strange characters or accents in the file name), just to be sure the problem was not the file name or extension.
cheers
A
