### ISSUE TITLE
Metadata parsing issue (except for MP3 files)

### ISSUE THREAD

**Issue by Go-rom** [albertobeta/PodcastGenerator#43]
Hello

I don't know if it's an issue or a missing feature but i get differences between MP3 files and the others like m4a or ogg.

First : metadata parsing works well only with mp3 files like title, embedded picture etc.
And second : bitrate and frequency rate are shown only with mp3 files.

Is there a way to display these informations with files other than mp3s ?

Thank you

**Comment by albertobeta** [comment]
at the moment is WAD (Works as Designed) since I am using an external library getid3 to extract metadata mostly from mp3. 

Stay tuned :) A brand-new and more modern version of Podcast Generator is expected in early 2018. [Read more](https://github.com/albertobeta/PodcastGenerator/issues/36#issuecomment-341741130)
