### ISSUE TITLE
$(theme)/functions.php usage

### ISSUE THREAD

**Issue by Fisiu** [albertobeta/PodcastGenerator#6]
I created own theme based on [flatly](https://bootswatch.com/flatly/) - it looks nice but I'd like to customize episodes' look. I found out I can use functions.php in $(theme) directory (according to [core/themes.php](https://github.com/albertobeta/PodcastGenerator/blob/master/core/themes.php#L34-L36)) but I don't know how to use it. Doc is silent about it.

Let's say I want to override
```php
function showPodcastEpisodes($all,$category)
```
to customize episode's look. How should I proceed with $(theme)/functions.php to accomplish this goal?

**Comment by albertobeta** [comment]
Hello,
first, themes.php is a legacy file I left for retrocompatibility with older themes. Use templates.php (to do so, simply include a file called theme.xml (it can be empty, for the moment) in your theme folder, see the [default_modern theme folder](https://github.com/albertobeta/PodcastGenerator/tree/master/themes/default_modern) as an example.
This said, the extension to functions.php is not documented cause it's not fully working yet. I'm planning to introduce this feature in future. 
You can't declare twice a PHP function or override it. The best (and most elegant) solution would be starting to use OOP for PG architecture, thus relying on classes rather than function (this will be a future step).
In the meanwhile you could create your own variant of showPodcastEpisodes() and disable (i.e. comment) the original one in functions.php. It's a hard-coded this way, but it would be the easiest solution at the moment.
BTW It would be great if, when your theme is ready, you share it. If it looks cool and is fully responsive, we can include it among the default PG themes (in return you get great visibility and improve the rank of your website if you place a link in the footer, see for instance [the credits of other contributors to PG themes in search engines](https://www.google.es/search?q=Theme+designed+by+RG+Creative&oq=Theme+designed+by+RG+Creative&aqs=chrome..69i57j69i64.360j0j7&sourceid=chrome&es_sm=119&ie=UTF-8#q=%22Theme+designed+by+RG+Creative%22))

**Comment by Fisiu** [comment]
Thanks for quick reply. My theme is based on [bootswatch flatly](https://bootswatch.com/flatly/) (bootstrap theme) so it's responsive by design ;-)
But as You already know, some css is hidden in functions.php file so I need to fix css in a hard way ;-)
Theme is similar to default_modern but is uses bootstrap 3. To be fully functional I need to modify PG sources. Anyway, here it is: https://copy.com/HyWbcntld19WZeXV

If desired, I can fork and then submit request.

Greetings,
Mariusz

**Comment by albertobeta** [comment]
The theme looks very nice and is lightweight :+1: 
Please feel free to fork the project and add flatly (I will definitely integrate it in the main branch).
Optionally, in regards to the "theme engine" of PG, if you want to improve its code in order to completely avoid hard-coded styles and make each theme even more independent from the main PG code, please go for it. If you add improvements to the theme engine (but ensure retrocompatibility with the current themes included out of the box in PG, since many users are adopting them) then I will definitely integrate also this new code into the main branch. Thank you in advance :)

**Comment by Fisiu** [comment]
Theme flatly has been submitted as #7.
