### ISSUE TITLE
Private Podcast

### ISSUE THREAD

**Issue by fujiyama17** [albertobeta/PodcastGenerator#62]
Hello!  This software is AMAZING!  Quick question, however.  I would like to make my website public, but my feed.xml and .mp3s private.  I can make all mp3s private by setting htaccess on the media folder, but not the feed.xml.  I don't mind the feed being public, in fact, I would like this, but then I don't think that the links to the feed.xml will be authenticated properly.  So, can I somehow get have Podcast Generator generate the xml feed in my media folder - therefore, the link to the podcast would be username:password@mywebsite/media/feed.xml.  This way, authenticating to the feed.xml will authenticate the user to everything the media folder, allowing the poscast subscription to work.

I looked at http://www.podcastgenerator.net/documentation/FAQ-change-RSS-URL - it seems that is for external RSS feeds.  That's not what I am looking for.

If anyone can help, I will send them some BTC for the effort, or a virtual high-five.  Thanks!

I know if has something to do with $feed_URL_replace = ".$url.$feed_dir."feed.xml"; or changing the $feed_dir... I am so close I can taste it.

**Comment by fujiyama17** [comment]
Jesus is a DJ.  I think I got it... Thank you, me.

**Comment by fujiyama17** [comment]
No!!! download.php creates a URL that can download the .mp3.  So close.  Can anyone help me configure download.php so that it generates a URL that forces the browser to access the media folder where the .mp3 is?

**Comment by albertobeta** [comment]
Unfortunately the password protected RSS feed feature is not coming out of the box with PG. You need to tweak the code so that the RSS feed requires authentication via a token for instance. Or you can try password protecting it via .htaccess as you would do with any other file, something like:
`<Location /feed.xml>
AuthName “My Private RSS Feed”
AuthType Basic
AuthUserFile /my/home/dir/rss.pw
Require valid-user
</Location>`
NB. Didn't try it, but most readers should request user and pwd.
