### ISSUE TITLE
Not able to upload podcasts

### ISSUE THREAD

**Issue by DavidmSRBC** [albertobeta/PodcastGenerator#72]
We have just recently been unable to upload our podcasts.  it keeps saying our max limit has been reached.  is there a file i can send you to look at to determine where the problem is?  any help would be appreciated.

David

**Comment by DavidmSRBC** [comment]
How do you get someone to help on an issue?  it has been 5 days

**Comment by albertobeta** [comment]
Not enough info to understand what the problem is. Try to upload a very small file as a test (e.g. <1MB) if it works then the "max limit" refer to the max size of a single file you can upload in your web hosting. This is a configuration setting that your hosting provider or server admin might have change. Were this the case see here: http://www.podcastgenerator.net/documentation/FAQ-max-upload-size
