### ISSUE TITLE
GDPR Consent on Podcast Generator server

### ISSUE THREAD

**Issue by asousapt** [albertobeta/PodcastGenerator#85]
Hello. 

I was thinking about the GDPR EU rules and I don't find any option on the server to setup a cookie consent for my podcast page.
Are you thinking to add that feature in future releases?

**Comment by Go-rom** [comment]
Hello

i'm just a PG user but i'm a little confused about your question related to the GDPR rules because PG doesn't collect any personal data.

And the cookie is just a session cookie, useful only in the case of logging in as the administrator of the podcast i guess.

**Comment by albertobeta** [comment]
Hi, interesting question.
PG is just a software [provided under a free license](https://github.com/albertobeta/PodcastGenerator/blob/master/LICENSE) and **you** are the ultimate responsible for GDPR compliance (including the data stored using PG). You also need to have a clear and comprehensive privacy policy and cookies policy.
My personal opinion is that the default cookies that PG uses constitute [legitimate interest](https://www.gdpreu.org/the-regulation/key-concepts/legitimate-interest/) since they are needed to store the current session, however, the use of plugins or code snippets within or outside PG code (e.g. Google Analytics, TagManager, etc...) imply new third party cookies which almost surely don't fit into this category. This is just a personal thought and I am not a lawyer therefore **my opinion does not replace legal counsel**.
If you need more info about GDPR you can start here https://www.eugdpr.org
